name: mgtl
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.13
  - pip=23.3.1
  - numpy=1.24.3
  - pip:
    - gradio==4.19.2
    - datasets==2.12.0
    - matplotlib==3.2.2
    - numpy==1.24.3
    - openai==1.13.3
    - scikit_learn==1.3.0
    - spacy==3.7.4
    - tqdm==4.66.2
    - transformers==4.31.0

